import React from "react";

export const WORKOUT_LIST_REQUEST = "WORKOUT_LIST_REQUEST"
export const WORKOUT_LIST_SUCCESS = "WORKOUT_LIST_SUCCESS"
export const WORKOUT_LIST_FAIL = "WORKOUT_LIST_FAIL"

export const WORKOUT_DETAIL_REQUEST = "WORKOUT_DETAIL_REQUEST"
export const WORKOUT_DETAIL_SUCCESS = "WORKOUT_DETAIL_SUCCESS"
export const WORKOUT_DETAIL_FAIL = "WORKOUT_DETAIL_FAIL"

export const WORKOUT_POST_REQUEST = "WORKOUT_POST_REQUEST"
export const WORKOUT_POST_SUCCESS = "WORKOUT_POST_SUCCESS"
export const WORKOUT_POST_FAIL = "WORKOUT_POST_FAIL"

export const WORKOUT_DELETE_REQUEST = "WORKOUT_DELETE_REQUEST"
export const WORKOUT_DELETE_SUCCESS = "WORKOUT_DELETE_SUCCESS"
export const WORKOUT_DELETE_FAIL = "WORKOUT_DELETE_FAIL"

export const WORKOUT_UPDATE_REQUEST = "WORKOUT_UPDATE_REQUEST"
export const WORKOUT_UPDATE_SUCCESS = "WORKOUT_UPDATE_SUCCESS"
export const WORKOUT_UPDATE_FAIL = "WORKOUT_UPDATE_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"



export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"